services:
  nuxt:
    container_name: nuxt
    build: 
      context: ./infra/docker/node
    volumes:
      - ./:/var/www/app
      - ./node_modules:/var/www/app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules: {}
